version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: zenda-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: zenda
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
